#pragma config(Hubs,  S1, HTMotor,  HTServo,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,           ,             tmotorNXT, openLoop)
#pragma config(Motor,  motorB,          tube,          tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          rackPinion,    tmotorNXT, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     motorRight,    tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     motorLeft,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     motorD,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     motorE,        tmotorTetrix, openLoop)
#pragma config(Servo,  srvo_S1_C2_1,    ringPlacer,           tServoStandard)
#pragma config(Servo,  srvo_S1_C2_2,    elServo,              tServoStandard)
#pragma config(Servo,  srvo_S1_C2_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C2_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"

void initializeRobot()
{
	nMotorEncoder[motorRight] = 0;
	nMotorEncoder[motorLeft] = 0;
	// Place code here to initialize servos to starting positions.
  // Sensors are automatically configured and setup by ROBOTC. They may need a brief time to stabilize.
	return;
}

task main()
{
	//while (1==1)
	//{
		//initializeRobot();
		waitForStart();
		motor[motorLeft] = 100;
		motor[motorRight] = 100;
		wait10Msec(400);
		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		motor[motorLeft] = 0;
		motor[motorRight] = 100;
		wait10Msec(125);
		motor[motorLeft] = 0;
		motor[motorRight] = 0;
		motor[motorLeft] = 100;
		motor[motorRight] = 100;
		wait10Msec(300);
		motor[motorLeft] = 0;
		motor[motorRight] = 0;
	//}
}
