//A Rishi Desai Production
#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          feedingMotorUno, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          flagPositionMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     tiltingMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     conveyorMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void conveyorForward() //conveyor feeds
{
	motor[conveyorMotor] = 100;
}
void conveyorBackward() //conveyor spits
{
	motor[conveyorMotor] = -100;
}
void conveyorStop() //conveyor stops
{
	motor[conveyorMotor] = 0;
}
void rollerSuck() //roller motors suck in blocks
{
	motor[feedingMotorUno] = 80;
	motor[feedingMotorDos] = 80;
}
void rollerSpit() //roller motors spit out blocks
{
	motor[feedingMotorUno] = -80;
	motor[feedingMotorDos] = -80;
}
void rollerStop() //roller motors stop running
{
	motor[feedingMotorUno] = 0;
	motor[feedingMotorDos] = 0;
}

void armUp()
{
	int ticksPerDegree2 = 5760/360;
	int nTicks =0;
	nTicks= ticksPerDegree2*150;
	nMotorEncoder[tiltingMotor]=0;
	while (abs(nMotorEncoder[tiltingMotor]) < nTicks)
	{
		motor[tiltingMotor]=75;
	}
	motor[tiltingMotor]=0;
	nMotorEncoder[tiltingMotor]=0;
}
void armDown()
{
	int ticksPerDegree3 = 5760/360;
	int nTicks =0;
	nTicks= ticksPerDegree3*120;
	nMotorEncoder[tiltingMotor]=0;
	while (abs(nMotorEncoder[tiltingMotor]) < nTicks)
	{
		motor[tiltingMotor]=-50;
	}
	motor[tiltingMotor]=0;
	nMotorEncoder[tiltingMotor]=0;
}




/*
task main()
{
}
*/
