#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     sonarSensor,    sensorSONAR)
#pragma config(Motor,  motorA,          feedingMotorUno, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          flagPositionMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     flagMotor,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     tiltingMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     conveyorMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "driveTrain_Functions.c"
#include "rollerAndArm_Functions.c"
float inchesMoved;

// task that turns left when an IR seeker finds the IR beacon underneath a box to put the autonomous block
task irRightTesting()
{
	while(true)
	{
		if(SensorValue(irSensor) == 5)
		{
			stopMotors();
			wait10Msec(40);
			moveForward(1, 80);
			wait10Msec(100);
			leftTwoWheelTurn(90, 80);
			wait10Msec(113);
			stopMotors();
			wait10Msec(30);
			/*
			motor[tiltingMotor] = 55;
			wait10Msec(138);
			motor[tiltingMotor] = 25;
			wait10Msec(5);
			motor[tiltingMotor] = 0;
			wait10Msec(10);
				motor[conveyorMotor] = 100;
				wait10Msec(250);
				motor[conveyorMotor] = 0;
				wait10Msec(50);
			motor[tiltingMotor] = -55;
			wait10Msec(60);
			motor[tiltingMotor] = -45;
			wait10Msec(40);
			motor[tiltingMotor] = 0;
			wait10Msec(10);
			stopMotors();
			wait10Msec(100);
			motor[frontLeftMotor] = 100;
			motor[backLeftMotor] = 100;
			motor[frontRightMotor] = 100;
			motor[backRightMotor] = -100;*/

			armUp();
			wait10Msec(100);
			conveyorForward();
			wait10Msec(150);
			conveyorStop();
			wait10Msec(50);
			armDown();
			wait10Msec(150);

			rightTwoWheelTurn(98, 40);
			wait10Msec(187);
			stopMotors();
			wait10Msec(100);
			break;
		}
		else
		{
			motor[frontLeftMotor] = 100;
			motor[frontRightMotor] = -100;
			motor[backRightMotor] = 100;
			motor[backLeftMotor] = 100;
		}
	}
}
// task that turns right when an IR seeker finds the IR beacon underneath a box to put the autonomous block
task irLeftTesting()
{
	while(true)
	{
		if(SensorValue(irSensor) == 5)
		{
			stopMotors();
			wait10Msec(40);
			moveBackward(3, 80);
			wait10Msec(100);
			rightTwoWheelTurn(100, 80);
			wait10Msec(120);
			stopMotors();
			wait10Msec(30);

			/*
			motor[tiltingMotor] = 55;
			wait10Msec(162);
			motor[tiltingMotor] = 25;
			wait10Msec(5);
			motor[tiltingMotor] = 0;
			wait10Msec(10);
				motor[conveyorMotor] = 100;
				wait10Msec(200);
				motor[conveyorMotor] = 0;
				wait10Msec(50);
			motor[tiltingMotor] = -45;
			wait10Msec(105);
			motor[tiltingMotor] = -25;
			wait10Msec(5);
			motor[tiltingMotor] = 0;
			wait10Msec(10);*/

			armUp();
			wait10Msec(100);
			conveyorForward();
			wait10Msec(120);
			conveyorStop();
			wait10Msec(100);
			armDown();
			wait10Msec(100);

			leftTwoWheelTurn(90, 80);
			wait10Msec(105);
			stopMotors();
			wait10Msec(100);
			break;
		}
		else
		{
			motor[frontLeftMotor] = 100;
			motor[frontRightMotor] = -100;
			motor[backRightMotor] = 100;
			motor[backLeftMotor] = 100;
		}
	}
}
/*
task main()
{
	StartTask(irTesting);
}
*/
