#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  motorA,          feedingMotor,  tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     conveyorMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C1_2,     motorE,        tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task moveConveyer()
{
	motor[conveyorMotor] = 100;
	wait10Msec(200000);
}
task feedIn()
{
	motor[feedingMotor] = -100;
	wait10Msec(200000);
}
task main()
{
	while(true)
	{
		StartTask(moveConveyer);
		StartTask(feedIn);
		wait10Msec(200);
		//StartTask(feedIn);
		//StartTask(moveConveyer);
	}
}
