#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     ultrasonicSensor, sensorSONAR)
#pragma config(Motor,  motorB,          rightRoller,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          leftRoller,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

int count = 0;
void rollerSuck()
{
	motor[leftRoller] = 80;
	motor[rightRoller] = 80;
}
void rollerSpit()
{
	motor[leftRoller] = -80;
	motor[rightRoller] = -80;
}
void rollerStop()
{
	motor[leftRoller] = 0;
	motor[rightRoller] = 0;
}
task blockCountTrap()
{
	bool sensorSeen = true;
	while(true)
	{
		if(sensorSeen)
		{
			if(SensorValue(ultrasonicSensor) > 10)
			{
				count ++;
				sensorSeen = false;
			}
		}
		else
		{
			if(SensorValue(ultrasonicSensor)< 10)
			{
				sensorSeen = true;
			}
		}
	}
}
task blockCountTime()
{
	while(true)
	{
		if (SensorValue(ultrasonicSensor) < 10)
		{
			wait10Msec(10);
			count++;
		}
	}
}
task main
{
	StartTask(blockCountTrap);
	while(true)
	{
		if (count < 5)
		{
			rollerSuck();
		}
		if (count == 4)
		{
			rollerStop();
		}
	}
}
