#pragma config(Sensor, S2,     touchSensor,    sensorTouch)
#pragma config(Sensor, S3,     ultrasonicSensor, sensorSONAR)
#pragma config(Motor,  motorA,          emptyMotor,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          leftRoller,    tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          rightRoller,   tmotorNXT, PIDControl, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void rollerSuck()
{
	motor[leftRoller] = 80;
	motor[rightRoller] = 80;
}
void rollerSpit()
{
	motor[leftRoller] = -80;
	motor[rightRoller] = -80;
}
void rollerStop()
{
	motor[leftRoller] = 0;
	motor[rightRoller] = 0;
}
int count = 0;
task main()
{
	while (1==1)
	{
		if (SensorValue(ultrasonicSensor) > 10)
		{
			rollerSuck();
		}
		else
		{
			rollerStop();
			wait10Msec(10);
			count++;
			rollerSuck();
		}
		if (count == 4)
		{
			rollerStop();
			break;
		}
	}
}
