#pragma config(Hubs,  S1, HTServo,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Servo,  srvo_S1_C1_1,    servo1,               tServoStandard)
#pragma config(Servo,  srvo_S1_C1_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C1_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float servoConversion = 1.4166666666667;
	while(true)
	{
		//servoChangeRate[servo1] = 20;
		servo[servo1] = 85*servoConversion;
		wait10Msec(400);
		servo[servo1] = 90*servoConversion;
		wait10Msec(400);
		servo[servo1] = 105*servoConversion;
		wait10Msec(400);
		servo[servo1] = 90*servoConversion;
		wait10Msec(400);
	}

}
