#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          feedingMotorUno, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     tiltingMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_2,     liftingMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_1,     conveyorMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     flagMotor,     tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"
#include "driveTrain_Functions.c"
#include "sensor_Functions.c"
#include "roller_Functions.c"
#include "it_Functions.c"

task main()
{
	waitForStart();
	nMotorEncoder[tiltingMotor] = 0;
	int targetTicks = 0;
	while(1==1)
	{
		writeDebugStreamLine("%d", abs(nMotorEncoder[tiltingMotor]));
		motor[frontLeftMotor] = ((100.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0));
		motor[backLeftMotor] = ((100.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0)*(joystick.joy1_y1/127.0));
		motor[frontRightMotor] = ((100.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0));
		motor[backRightMotor] = ((100.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0)*(joystick.joy1_y2/127.0));
		motor[feedingMotorUno] = ((100.0)*(joystick.joy2_y1/127.0)*(joystick.joy2_y1/127.0)*(joystick.joy2_y1/127.0));
		motor[feedingMotorDos] = ((100.0)*(joystick.joy2_y1/127.0)*(joystick.joy2_y1/127.0)*(joystick.joy2_y1/127.0));
		motor[conveyorMotor] = ((100.0)*(joystick.joy2_y2/127.0)*(joystick.joy2_y2/127.0)*(joystick.joy2_y2/127.0));


		tilting(targetTicks);

		if(joy2Btn(1))
		{
			targetTicks = 300;
			/*if(abs(nMotorEncoder[tiltingMotor]) < targetTicks)
			{
				motor[tiltingMotor] = 100;
			}
			else
			{
				motor[tiltingMotor] = 0;
			}*/
		}
		if(joy2Btn(2))
		{
			if(abs(nMotorEncoder[tiltingMotor]) < 75)
			{
				motor[tiltingMotor] = -100;
			}
			else
			{
				motor[tiltingMotor] = 0;
			}
		}
		if(joy2Btn(4))
		{
			motor[tiltingMotor] = 0;
			//StartTask(rollerRun);
		}
		if(joy2Btn(7))
		{
			motor[liftingMotor] = -100;
		}
		if(joy2Btn(8))
		{
			motor[flagMotor] = 100;
		}
		if(joystick.joy2_TopHat == 0)
	  {
	  	if(abs(nMotorEncoder[tiltingMotor]) < 75)
			{
				motor[tiltingMotor] = 100;
			}
			else
			{
				motor[tiltingMotor] = 0;
			}
	  }
	  if(joystick.joy2_TopHat == 2)
	  {
	  	if(abs(nMotorEncoder[tiltingMotor]) < 75)
			{
				motor[tiltingMotor] = 100;
			}
			else
			{
				motor[tiltingMotor] = 0;
			}
	  }
	  if(joystick.joy2_TopHat == 4)
	  {
	  	if(abs(nMotorEncoder[tiltingMotor]) < 75)
			{
				motor[tiltingMotor] = -100;
			}
			else
			{
				motor[tiltingMotor] = 0;
			}
	  }
	  if(joystick.joy2_TopHat == 6)
	  {
	  	if(abs(nMotorEncoder[tiltingMotor]) < 75)
			{
				motor[tiltingMotor] = 100;
			}
			else
			{
				motor[tiltingMotor] = 0;
			}
	  }
	}
}
