#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     lightSensor,    sensorLightActive)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touchSensor,    sensorTouch)
#pragma config(Motor,  motorA,          feedingMotorUno, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     frontRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     backRightMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     tiltingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     liftingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     conveyorMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     flagMotor,     tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float pie = 3.14159;
float track = 14.5;
float halfTrack = track / 2;
float wheelDiam = 3.75;
float wheelRadius = 1.875;
float wheelCircumference = wheelDiam * PI;
float ticksPerInches =  2880 / (wheelCircumference);
float halfRobotCircumference = track*pie;
float robotCircumference = track*2*pie;
//float inchesPerDegreeOneWheel = wheelCircumference/(robotCircumference*4);
//float inchesPerDegreeTwoWheel = wheelCircumference/(halfRobotCircumference;


// function that gets the robot to move forward a certain number of inches and power, inputed as a parameter
void moveForward(float inchesMoved, int motorSpeed)
{
	float nticks = 0;
	nticks = abs(inchesMoved * ticksPerInches);
	float nticks2 = nticks * 22.5 / 26;
	nMotorEncoder[backLeftMotor] = 0;
	writeDebugStreamLine("number of ticks that our robot has to move.");
	writeDebugStreamLine("%d", nticks2);
	while (abs(nMotorEncoder[backLeftMotor]) < nticks2)
	{
			motor[frontLeftMotor] = motorSpeed;
			motor[frontRightMotor] = motorSpeed - 0.5;
			motor[backRightMotor] = motorSpeed;
			motor[backLeftMotor] = motorSpeed;
			motorSpeed -= 0.005;
	}
	motor[frontRightMotor] = 0;
	motor[frontLeftMotor] = 0;
	motor[backRightMotor] = 0;
	motor[backLeftMotor] = 0;
	//writeDebugStreamLine("%d", nMotorEncoder[backLeftMotor]);
}

// function that gets the robot to move backward a certain number of inches and power, inputed as a parameter
void moveBackward(float inchesMoved, int motorSpeed)
{
	float nticks = 0;
	nticks =  abs(inchesMoved *ticksPerInches);
	float nticks2 = nticks * 22.5 / 26;
	writeDebugStreamLine("number of ticks that our robot has to move.");
	writeDebugStreamLine("%d", nticks);
	nMotorEncoder[backLeftMotor] = 0;
	while(abs(nMotorEncoder[backLeftMotor]) < nticks2)
	{
		motor[frontRightMotor] = -motorSpeed;
		motor[frontLeftMotor] = -motorSpeed;
		motor[backRightMotor] = -motorSpeed;
		motor[backLeftMotor] = -motorSpeed;
	}
	motor[frontRightMotor] = 0;
	motor[frontLeftMotor] = 0;
	motor[backRightMotor] = 0;
	motor[backLeftMotor] = 0;
	//writeDebugStreamLine("%d", nMotorEncoder[backLeftMotor]);
}

/*
// function that allows the robot to turn left with  one wheel  stopped and one wheel moving.
void leftOneWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*track)/(wheelRadius));
	nticks *= 1.43850;
	nMotorEncoder[backRightMotor]=0;
	while(nMotorEncoder[backRightMotor] < nticks*8){
		motor[frontRightMotor] = motorSpeed;
		motor[frontLeftMotor] = 0;
		motor[backRightMotor] = motorSpeed;
		motor[backLeftMotor] = 0;
		motorSpeed += 0.005;
	}
	nticks =0;
}

// function that allows the robot to turn right with  one wheel  stopped and one wheel moving.
void rightOneWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*track)/(wheelRadius));
	nticks *= 1.43850;
	nMotorEncoder[backLeftMotor]=0;
	while(nMotorEncoder[backLeftMotor] < nticks*8){
		motor[frontRightMotor] = 0;
		motor[frontLeftMotor] = motorSpeed;
		motor[backRightMotor] = 0;
		motor[backLeftMotor] = motorSpeed;
		motorSpeed -= 0.005;
	}
	nticks = 0;
}
*/

// function that gets the robot to turn left with two wheels, for a certain number of degrees at a certain power, inputed as a parameter
void leftTwoWheelTurn(int degreesMoved, int motorSpeed)
{
	float nticks =0;
	float negMSpeed = -motorSpeed;
	nticks = abs((degreesMoved*halfTrack)/(wheelRadius));
	nticks = nticks * 0.75 *2 / 3;
	nMotorEncoder[backLeftMotor]=0;
	while(abs(nMotorEncoder[backLeftMotor]) < nticks*4)
	{
		motor[frontRightMotor] = motorSpeed;
		motor[frontLeftMotor] = negMSpeed;
		motor[backRightMotor] = motorSpeed;
		motor[backLeftMotor] = negMSpeed;
		motorSpeed -= 0.005;
		negMSpeed += 0.005;
	}
	nticks =0;
}

// function that gets the robot turn right with two wheels, for a certain number of degrees at a cetain power, inputed as a paramter
void  rightTwoWheelTurn(int degreesMoved, int motorSpeed)
{
	float nticks = 0;
	float negMSpeed = -motorSpeed;
	nticks = abs((degreesMoved*halfTrack)/(wheelRadius));
	nticks= nticks* 1.3 * 2/ 3;
	nMotorEncoder[backLeftMotor]=0;
	while(nMotorEncoder[backLeftMotor] < nticks)
	{
		motor[frontRightMotor] = negMSpeed;
		motor[frontLeftMotor] = motorSpeed;
		motor[backRightMotor] = negMSpeed;
		motor[backLeftMotor] = motorSpeed;
		motorSpeed -= 0.005;
		negMSpeed += 0.005;
	}
}


void stopMotors()
{
	motor[frontRightMotor] = 0;
	motor[frontLeftMotor] = 0;
	motor[backRightMotor] = 0;
	motor[backLeftMotor] = 0;
}

/*
task main()
{
	leftTwoWheelTurn(45, 80);
}
*/
