#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ultrasonicSensor, sensorSONAR)
#pragma config(Sensor, S4,     lightSensor,    sensorLightInactive)
#pragma config(Motor,  motorA,          conveyerMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rollerMotor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     backRightMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     frontLeftMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "movingAndTurning.c"
float inchesMoved;
task irTesting()
{
	while(true)
	{
		if(SensorValue(irSensor) == 5)
		{
			inchesMoved= nMotorEncoder[backLeftMotor]/ticksPerInches;
			wait10Msec(40);
			moveForward(3, 80);
			wait10Msec(50);
			leftTwoWheelTurn(90, 80);
			wait10Msec(86);
			motor[frontLeftMotor] = 0;
			motor[frontRightMotor] = 0;
			motor[backRightMotor] = 0;
			motor[backLeftMotor] = 0;
			wait10Msec(100);
			rightTwoWheelTurn(90, 80);
			wait10Msec(102);
			break;
		}
		else if(SensorValue(irSensor) >= 1 || SensorValue(irSensor) <= 4)
		{
			motor[frontLeftMotor] = 100;
			motor[frontRightMotor] = 100;
			motor[backRightMotor] = 100;
			motor[backLeftMotor] = 100;
		}
		else if (SensorValue(irSensor) >= 6 || SensorValue(irSensor) <= 9)
		{
			motor[frontLeftMotor] = 100;
			motor[frontRightMotor] = 100;
			motor[backRightMotor] = 100;
			motor[backLeftMotor] = 100;
		}
	}
}


//task main()
//{

//StartTask(irTesting);



//}
