#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ultrasonicSensor, sensorSONAR)
#pragma config(Sensor, S4,     lightSensor,    sensorLightInactive)
#pragma config(Motor,  motorA,          conveyerMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rollerMotor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     backRightMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     frontLeftMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "movingAndTurning.c"
#include "irContinuousTest.c"

void irPositionTest(int inches)
{
	wait10Msec(100);
	inches=inches * 1.1612;
	if(inches<=12)
	{
		moveForward(69, 80);
	}
		else if(inches>=12 && inches<=22)
	{

		moveForward(59, 80);
	}
		else if(inches>=22 && inches<=41)
	{

		moveForward(40, 80);
	}else if(inches>=41 && inches<=50)
	{
			moveForward(29, 80);
	}


}

task main()
{

	moveForward(5, 80);
	wait10Msec(50);
	rightTwoWheelTurn(45, 50);
	wait10Msec(53);
	//moveBackward(1, 80);
	//wait10Msec(50);
	StartTask(irTesting);

	wait10Msec(110);
	//StopTask(irTesting);
	irPositionTest(inchesMoved);
	/*/wait10Msec(50);
	leftTwoWheelTurn(48, 50);
	wait10Msec(58);
	moveForward(52, 80);
	wait10Msec(50);
	rightTwoWheelTurn(53, 50);
	wait10Msec(75);
	moveBackward(67.5, 80);
	wait10Msec(50);*/

	//moveForward(40, 80);


	//writeDebugStreamLine("inches moved: %d", inchesMoved);
}
