#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Sensor, S2,     touchSensorDos,    sensorLightActive)
#pragma config(Sensor, S3,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     touchSensorUno,    sensorTouch)
#pragma config(Motor,  motorA,          feedingMotorUno, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          feedingMotorDos, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     frontLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     flagMotor,     tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C2_2,     liftingMotor,  tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C3_1,     frontRightMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     backRightMotor, tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     tiltingMotor,  tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_2,     conveyorMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "driveTrain_Functions.c"
#include "sensor_Functions.c"



task main()
{
	moveForward(7, 80);
	wait10Msec(50);
	stopMotors();
	wait10Msec(30);
	rightTwoWheelTurn(45, 50);
	wait10Msec(65);
	stopMotors();
	wait10Msec(30);
	moveBackward(2, 80);
	wait10Msec(50);
	stopMotors();
	wait10Msec(30);
	StartTask(irRightTesting);
	wait10Msec(800);
	StopTask(irRightTesting);
	while (SensorValue[touchSensorDos] == 0)
	{
		motor[frontLeftMotor] = 100;
		motor[frontRightMotor] = 100;
		motor[backRightMotor] = 100;
		motor[backLeftMotor] = 100;
	}
	stopMotors();
	wait10Msec(30);
	while (SensorValue[touchSensorUno] == 0)
	{
		motor[frontLeftMotor] = 100;
		motor[frontRightMotor] = 0;
		motor[backRightMotor] = 0;
		motor[backLeftMotor] = 100;
	}
	stopMotors();
	wait10Msec(30);
	/*moveForward(52, 80);
	wait10Msec(50);
	rightTwoWheelTurn(53, 50);
	wait10Msec(75);
	moveBackward(67.5, 80);
	wait10Msec(50);
	moveForward(40, 80);
	//writeDebugStreamLine("inches moved: %d", inchesMoved);*/
}
