#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Sensor, S2,     irSensor,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     ultrasonicSensor, sensorSONAR)
#pragma config(Sensor, S4,     lightSensor,    sensorLightInactive)
#pragma config(Motor,  motorA,          conveyerMotor, tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorB,          rollerMotor,   tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     backRightMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     frontLeftMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "movingAndTurning.c"
#include "irContinuousTest.c"

void irPositionTest (){
	float inchesMoved= (nMotorEncoder[backLeftMotor]/ticksPerInches)+4;
	if(inchesMoved<=12){
		moveForward(69, 80);
	}else if(inchesMoved>=12 && inchesMoved<=22){

		moveForward(59, 80);
	}else if(inchesMoved>=22 && inchesMoved<=41){

		moveForward(40, 80);
	}else if(inchesMoved>=41 && inchesMoved<=50){

		moveForward(29, 80);
	}


}

task main()
{
<<<<<<< HEAD:WarriorBorgs FTC 2013/realCode/rightAutoP.c
	//moveForward(7, 80);
	//wait10Msec(50);
	//leftTwoWheelTurn(45, 50);
	//wait10Msec(49.5);
	//moveForward(38.75, 80);
	//wait10Msec(50);
	//rightTwoWheelTurn(45, 50);
	//wait10Msec(145);
	//stopMotors();
	//wait10Msec(100);
	//leftTwoWheelTurn(42, 50);
	//wait10Msec(127);
	//moveForward(16, 80);
	//wait10Msec(50);
	//rightTwoWheelTurn(48, 50);
	//wait10Msec(70);
	//moveForward(52, 80);
	//wait10Msec(50);
	//leftTwoWheelTurn(53, 50);
	//wait10Msec(58);
	//moveBackward(69, 80);
	//wait10Msec(50);

	moveBackward(24, 80);

	writeDebugStreamLine("inches moved: %d", inchesMoved);
=======
	moveForward(8, 80);
	wait10Msec(50);
	rightTwoWheelTurn(30, 50);
	wait10Msec(40);
	stopMotors();
	wait10Msec(100);
	rightTwoWheelTurn(15, 50);
	wait10Msec(65);
	moveForward(58, 80);
	wait10Msec(50);
	rightTwoWheelTurn(90, 50);
	wait10Msec(91);
	moveBackward(53, 80);
	wait10Msec(50);
>>>>>>> 15afc0266fe0664b63daeaa75c7626b77d6737e3:WarriorBorgs FTC 2013/realCode/rightBack22Auto.c
}
