#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTMotor,  HTMotor)
#pragma config(Motor,  mtr_S1_C1_1,     backRightMotor, tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     frontRightMotor, tmotorTetrix, openLoop, reversed)
#pragma config(Motor,  mtr_S1_C2_1,     motorF,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     motorG,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_1,     motorH,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C3_2,     motorI,        tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C4_1,     backLeftMotor, tmotorTetrix, openLoop, encoder)
#pragma config(Motor,  mtr_S1_C4_2,     frontLeftMotor, tmotorTetrix, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

float pie = 3.14159;
float track = 14.5;
float halfTrack = track / 2;
float wheelDiam = 3.75;
float wheelRadius = 1.875;
float wheelCircumference = wheelDiam * PI;
float ticksPerInches =  720 / (wheelCircumference);
float halfRobotCircumference = track*pie;
float robotCircumference = track*2*pie;
//float inchesPerDegreeOneWheel = wheelCircumference/(robotCircumference*4);
//float inchesPerDegreeTwoWheel = wheelCircumference/(halfRobotCircumference;


// function that allows the robot to move forward.
void moveForward(float inchesMoved, int motorSpeed){
	float nticks = 0;
	nticks = abs(inchesMoved * ticksPerInches);
	nMotorEncoder[backRightMotor] = 0;
	writeDebugStreamLine("number of ticks that our robot has to move.");
	writeDebugStreamLine("%d", nticks);
	while (abs(nMotorEncoder[backRightMotor]) < nticks){
		motor[frontRightMotor] = motorSpeed;
		motor[frontLeftMotor] = motorSpeed;
		motor[backRightMotor] = motorSpeed;
		motor[backLeftMotor] = motorSpeed;
	}

	writeDebugStreamLine("%d", nMotorEncoder[backRightMotor]);
}

// function that allows the robot to move backward.
void moveBackward(float inchesMoved, int motorSpeed){
	float nticks = 0;
	nticks =  abs(inchesMoved *ticksPerInches);
	writeDebugStreamLine("number of ticks that our robot has to move.");
	writeDebugStreamLine("%d", nticks);
	nMotorEncoder[backLeftMotor] = 0;
	while(abs(nMotorEncoder[backLeftMotor]) < nticks){
		motor[frontRightMotor] = -motorSpeed;
		motor[frontLeftMotor] = -motorSpeed;
		motor[backRightMotor] = -motorSpeed;
		motor[backLeftMotor] = -motorSpeed;
	}
	writeDebugStreamLine("%d", nMotorEncoder[backLeftMotor]);
}

// function that allows the robot to turn left with  one wheel  stopped and one wheel moving.
void leftOneWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*track)/(wheelRadius*4));
	nMotorEncoder[frontRightMotor]=0;
	while(nMotorEncoder[frontRightMotor] < nticks){
		motor[frontRightMotor] = motorSpeed;
		motor[frontLeftMotor] = 0;
		motor[backRightMotor] = motorSpeed;
		motor[backLeftMotor] = 0;
	}
	nticks =0;
}

// function that allows the robot to turn right with  one wheel  stopped and one wheel moving.
void rightOneWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*track)/(wheelRadius*1440));
	nMotorEncoder[frontRightMotor]=0;
	while(nMotorEncoder[frontRightMotor] < nticks){
		motor[frontRightMotor] = 0;
		motor[frontLeftMotor] = motorSpeed;
		motor[backRightMotor] = 0;
		motor[backLeftMotor] = motorSpeed;
	}
	nticks = 0;
}
// function that allows the robot to turn left with two wheels moving the opposite way.
void leftTwoWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*halfTrack)/(4*wheelRadius));
	nMotorEncoder[frontRightMotor]=0;
	while(nMotorEncoder[frontRightMotor] < nticks){
		motor[frontRightMotor] = motorSpeed;
		motor[frontLeftMotor] = -motorSpeed;
		motor[backRightMotor] = motorSpeed;
		motor[backLeftMotor] = -motorSpeed;
	}
	nticks =0;
}

// function that allows the robot to turn right with two wheels moving the opposite way.
void  rightTwoWheelTurn(int degreesMoved, int motorSpeed){
	float nticks = 0;
	nticks = abs((degreesMoved*halfTrack)/(4*wheelRadius));
	nMotorEncoder[frontLeftMotor]=0;
	while(nMotorEncoder[frontLeftMotor] < nticks){
		motor[frontRightMotor] = -motorSpeed;
		motor[frontLeftMotor] = motorSpeed;
		motor[backRightMotor] = -motorSpeed;
		motor[backLeftMotor] = motorSpeed;
	}

}
task main()
{
	moveForward(24, 80);
}
