#pragma config(Hubs,  S1, HTMotor,  none,     none,     none)
#pragma config(Sensor, S1,     ,               sensorI2CMuxController)
#pragma config(Motor,  mtr_S1_C1_1,     leftMotor,     tmotorTetrix, openLoop, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     rightMotor,    tmotorTetrix, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//


float pie = 3.14159;
float track = 14.5;
float halfTrack = track / 2;
float wheelDiam = 3.5;
float wheelRadius = 1.75;
float wheelCircumference = wheelDiam * PI *1.000066666;
float ticksPerInches =  2880/ (wheelCircumference);
float halfRobotCircumference = track*pie;
float robotCircumference = track*2*pie;
//float inchesPerDegreeOneWheel = wheelCircumference/(robotCircumference*4);
//float inchesPerDegreeTwoWheel = wheelCircumference/(halfRobotCircumference;


// function that allows the robot to move forward.
void moveForward(float inchesMoved, int motorSpeed){
	float nticks = 0;
	nticks =  abs(inchesMoved * ticksPerInches);
	nMotorEncoder[rightMotor] = 0;
	writeDebugStreamLine("number of ticks that our robot has to move.");
	writeDebugStreamLine("%d", nticks);
	while (abs(nMotorEncoder[rightMotor]) < nticks){
		motor[rightMotor] = motorSpeed;
		motor[leftMotor] = motorSpeed;

	}

	writeDebugStreamLine("%d", nMotorEncoder[rightMotor]);
}

// function that allows the robot to move backward.
void moveBackward(float inchesMoved, int motorSpeed){
	float nticks = 0;
	nticks =  abs(inchesMoved *ticksPerInches);
	writeDebugStreamLine("number of ticks that our robot has to move.");
	writeDebugStreamLine("%d", nticks);
	nMotorEncoder[rightMotor] = 0;
	while(abs(nMotorEncoder[rightMotor]) < nticks){
		motor[rightMotor] = -motorSpeed;
		motor[leftMotor] = -motorSpeed;
	}
	writeDebugStreamLine("%d", nMotorEncoder[rightMotor]);
}

// function that allows the robot to turn left with  one wheel  stopped and one wheel moving.
void leftOneWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*track)/(wheelRadius*4));
	nMotorEncoder[rightMotor]=0;
	while(nMotorEncoder[rightMotor] < nticks){
		motor[rightMotor] = motorSpeed;
		motor[leftMotor] = 0;
	}
	nticks =0;
}

// function that allows the robot to turn right with  one wheel  stopped and one wheel moving.
void rightOneWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*track)/(wheelRadius*1440));
	nMotorEncoder[rightMotor]=0;
	while(nMotorEncoder[rightMotor] < nticks){
		motor[rightMotor] = 0;
		motor[leftMotor] = motorSpeed;
	}
	nticks = 0;
}
// function that allows the robot to turn left with two wheels moving the opposite way.
void leftTwoWheelTurn(int degreesMoved, int motorSpeed){
	float nticks =0;
	nticks = abs((degreesMoved*halfTrack)/(4*wheelRadius));
	nMotorEncoder[rightMotor]=0;
	while(nMotorEncoder[rightMotor] < nticks){
		motor[rightMotor] = motorSpeed;
		motor[leftMotor] = -motorSpeed;
	}
	nticks =0;
}

// function that allows the robot to turn right with two wheels moving the opposite way.
void  rightTwoWheelTurn(int degreesMoved, int motorSpeed){
	float nticks = 0;
	nticks = abs((degreesMoved*halfTrack)/(4*wheelRadius));
	nMotorEncoder[leftMotor]=0;
	while(nMotorEncoder[leftMotor] < nticks){
		motor[rightMotor] = -motorSpeed;
		motor[leftMotor] = motorSpeed;
	}

}
task main()
{
	moveForward(24, 50);
}
